<a href="https://colab.research.google.com/github/znoble360/cap4630/blob/master/HW_4/HW_4_P2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Problem 2

##Imports

In [0]:
import numpy as np

##maxpooling2d

assumes valid padding

In [0]:
def maxpooling2d(input_mat, s):
    if s > input_mat.shape[0]:
        return []
   
    #size of the output_mat on the x and y axes
    output_mat_x = int(input_mat.shape[0] / s)
    output_mat_y = int(input_mat.shape[1] / s)
    
    # empty matrix to hold the results to return
    output_mat = np.empty((output_mat_x, output_mat_y))

    # while the kernel_mat is still in the bounds of the input_mat, slide the kernel down
    for i in range(output_mat_x):
        # while kernel_mat is still in the bounds of the input_mat, slide the kernel right
        for j in range(output_mat_y):
            # applies the kernel to the input_mat and stores the summation of the result to output_mat[i][j]
            input_slice = input_mat[i*s:(i+1)*s,j*s:(j+1)*s]
            output_mat[i][j] = np.amax(input_slice)
    
    return output_mat

In [0]:
#import skimage.measure

input_mat = []
expected_mat = []
s = []
input_mat.append(np.array([[1, 2, 1, 2],
                           [2, 4, 2, 1],
                           [1, 2, 4, 2],
                           [2, 1, 2, 1]]))
s.append(2)

expected_mat.append(np.array([[4, 2],
                              [2, 4]]))

input_mat.append(np.array([[1, 2, 1, 2, 4, 5],
                           [2, 4, 2, 1, 0, 3],
                           [1, 2, 4, 2, 4, 5],
                           [2, 1, 2, 1, 2, 1],
                           [1, 1, 2, 3, 1, 2]]))
s.append(2)

expected_mat.append([[4, 2, 5],
                     [2, 4, 5],
                     [1, 3, 2]])


for i in range(len(input_mat)):
  # uncomment top line and comment second line to test code
  output_mat = maxpooling2d(input_mat[i], s[i])
  #output_mat = skimage.measure.block_reduce(input_mat[i], (s[i],s[i]), np.max)

  print(output_mat)

  if np.array_equal(output_mat, expected_mat[i]):
    print("Correct output!")
  else:
    print("Incorrect output!")


[[4. 2.]
 [2. 4.]]
Correct output!
[[4. 2. 5.]
 [2. 4. 5.]]
Incorrect output!


according to the homework description, the second result should be correct, since valid padding should be used. 