<a href="https://colab.research.google.com/github/znoble360/cap4630/blob/master/HW_4/HW_4_P1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Problem 1:

##Imports and References

test cases from https://github.com/schneider128k/machine_learning_course/blob/master/homework/2020_spring/test_cases_for_problems_1_2_homework_4.ipynb

In [0]:
import numpy as np

In [0]:
# takes 2 2d numpy arrays input_mat and kernel_mat and multiplies element input_mat[x][y] with kernel_mat[x][y]
# returns a 2d numpy array with the results
def filter_mat(input_mat, kernel_mat):
    result = np.empty((input_mat.shape[0], input_mat.shape[1]))

    for i in range(input_mat.shape[0]):
        for j in range(input_mat.shape[1]):
            result[i][j] = input_mat[i][j] * kernel_mat[i][j]
            
    return result

##conv2d

In [0]:
def conv2d(input_mat, kernel_mat):
    if kernel_mat.shape[0] > input_mat.shape[0]:
        return []

    # flip the kernel 180 degrees
    #fliped_kernel_mat = np.rot90(kernel_mat, 2)
   
    # size of the kernel on the x and y axes
    #kernel_x = fliped_kernel_mat.shape[0]
    #kernel_y = fliped_kernel_mat.shape[1]

    # size of the kernel on the x and y axes
    kernel_x = kernel_mat.shape[0]
    kernel_y = kernel_mat.shape[1]
 
    #   
 
    # size of the output_mat on the x and y axes
    output_mat_x = input_mat.shape[0] - kernel_x + 1
    output_mat_y = input_mat.shape[1] - kernel_y + 1

    # empty matrix to hold the results to return
    output_mat = np.empty((output_mat_x, output_mat_y))

    # while the fliped_kernel_mat is still in the bounds of the input_mat, slide the kernel down
    for i in range(output_mat_x):
        # while fliped_kernel_mat is still in the bounds of the input_mat, slide the kernel right
        for j in range(output_mat_y):
            # applies the kernel to the input_mat and stores the summation of the result to output_mat[i][j]
            input_slice = input_mat[i:i+kernel_x,j:j+kernel_y]
            output_mat[i][j] = np.sum(filter_mat(input_slice, kernel_mat))
    
    return output_mat

In [0]:
#from scipy import signal

input_mat = []
kernel_mat = []
expected_mat = []

# test case 1
input_mat.append(np.array([[1, 2, 1, 2],
                           [2, 1, 2, 1],
                           [1, 2, 1, 2],
                           [2, 1, 2, 1]]))

kernel_mat.append(np.array([[1, 0],
                            [0, 1]]))

expected_mat.append(np.array([[2, 4, 2],
                              [4, 2, 4],
                              [2, 4, 2]]))

# test case 2
input_mat.append(np.array([[1, 0, 0, 0],
                           [0, 1, 0, 0],
                           [0, 0, 1, 0],
                           [0, 0, 0, 1]]))

kernel_mat.append(np.array([[1, 0], 
                            [0, 1]]))

expected_mat.append(np.array([[2, 0, 0],
                              [0, 2, 0],
                              [0, 0, 2]]))


# test case 3
input_mat.append(np.array([[1, 0, 0, 0],
                           [0, 1, 0, 0],
                           [0, 0, 1, 0],
                           [0, 0, 0, 1]]))

kernel_mat.append(np.array([[1, -1],
                            [-1, 0]]))

expected_mat.append(np.array([[ 1, -1,  0],
                              [-1,  1, -1],
                              [ 0, -1,  1]]))


# test case 4
input_mat.append(np.array([[1, 0, 0, 0],
                           [0, 1, 0, 0],
                           [0, 0, 1, 0],
                           [0, 0, 0, 1]]))

kernel_mat.append(np.array([[1, 0, 0, 0],
                           [0, 1, 0, 0],
                           [0, 0, 1, 0],
                           [0, 0, 0, 1]]))

expected_mat.append(np.array([[4]]))


# test case 5 - should either through an error, or return empty matrix
input_mat.append(np.array([[1, -1],
                           [-1, 0]]))

kernel_mat.append(np.array([[1, 0, 0, 0],
                            [0, 1, 0, 0],
                            [0, 0, 1, 0],
                            [0, 0, 0, 1]]))

expected_mat.append([])



for i in range(len(input_mat)):
  # uncomment line for student code testing
  output_mat = conv2d(input_mat[i], kernel_mat[i])

  # uncomment lines below (and comment line above) for generating test cases.
  #if input_mat[i].shape[0] < kernel_mat[i].shape[0]:
  #  output_mat = []
  #else:
  #  output_mat = signal.convolve2d(input_mat[i], kernel_mat[i], mode='valid')

  print(output_mat)
  if np.array_equal(output_mat, expected_mat[i]):
    print("Correct output!\n")
  else:
    print("Incorrect output!\n")


[[2. 4. 2.]
 [4. 2. 4.]
 [2. 4. 2.]]
Correct output!

[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]
Correct output!

[[ 1. -1.  0.]
 [-1.  1. -1.]
 [ 0. -1.  1.]]
Correct output!

[[4.]]
Correct output!

[]
Correct output!

