<a href="https://colab.research.google.com/github/znoble360/cap4630/blob/master/HW_1/multiply_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The function multiply_matrices(array) takes an array of numpy arrays and outputs their product. If the array contains incompatible arrays or is empty, it throws an exception. <br>
Two numpy arrays are compatable when the number of columns in the first array is equal to the number of rows in the second array. In this example, matrices A and B are compatable.

\begin{equation*}
A = 
\begin{pmatrix}
1 & 2 \\
3 & 4 \\
5 & 6
\end{pmatrix}
\quad
B = 
\begin{pmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{pmatrix}
\end{equation*}
<br>
In this example, matrices C and D are not compatable.

\begin{equation*}
C = 
\begin{pmatrix}
9 & 8 \\
7 & 6 \\
5 & 4
\end{pmatrix}
\quad
D = 
\begin{pmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{pmatrix}
\end{equation*}

In [0]:
import numpy as np

class Error(Exception) : 
    """Base class for exceptions in this module."""

class EmptyArrayError(Error) :
    """Exception raised when expecting a populated array but receiving an empty array"""
    def __init__(self, message):
        self.message = message 
    pass

class IncompatibleArraysError(Error) :
    """Exception raised when trying to multiply 2 incompatible arrays"""

    def __init__(self, message, arrays):
        self.message = message
        self.arrays = arrays
    pass

A = np.array([[1,2], [3,4], [5,6]])
B = np.array([[1,2,3], [4,5,6]])
C = np.array([[9,8], [7,6], [5,4]])
D = np.array([[1,2,3], [4,5,6], [7,8,9]])

def multiply_matrices(matrices):

    if(len(matrices) < 1):
        raise EmptyArrayError("expected array of size greater than 0")
        return
    

    result = matrices[0]
    for i in range(1, len(matrices)):
        try:
            result = np.matmul(result, matrices[i])

        except ValueError:
            raise IncompatibleArraysError("these two arrays are incompatible:", [result, matrices[i]])
            return


    return result


In [27]:
# test cases that should result in a matrix product
print("These should work")
print()
print(multiply_matrices([A,B,D]))
print()
print(multiply_matrices([A,B]))
print()
print(multiply_matrices([B,C]))
print()

These should work

[[162 198 234]
 [354 432 510]
 [546 666 786]]

[[ 9 12 15]
 [19 26 33]
 [29 40 51]]

[[ 38  32]
 [101  86]]



In [49]:
# should raise EmptyArrayError
print("empty array:")
print(multiply_matrices([]))

empty array:


EmptyArrayError: ignored

In [48]:
# should throw IncompatibleArraysError
print("incompatible array:")
print(multiply_matrices([C,D]))

incompatible array:


IncompatibleArraysError: ignored